version: '3.7'
services:
  rabbit:
    image: rabbitmq:3-management
    restart: always
    ports:
      - 5672:5672
      - 15672:15672

  api:
    build: .
    image: assignment-4-api
    restart: always
    ports:
      - 8000:8000
    environment:
      MONGO_DATABASE: ${MONGO_DATABASE}
      MONGO_USER: ${MONGO_USER}
      MONGO_PASSWORD: ${MONGO_PASSWORD}
      MONGO_HOST: mongodb
      MONGO_PORT: 27017
      RABBITMQ_HOST: rabbit
    depends_on:
      - rabbit
    links:
      - rabbit

  mongodb:
    image: mongo:latest
    restart: always
    volumes:
      - mongo-data:/data/db
      - ./db-init/:/docker-entrypoint-initdb.d
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_ROOT_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_DATABASE}
      MONGO_USER: ${MONGO_USER}
      MONGO_PASSWORD: ${MONGO_PASSWORD}

  sizeWorker:
    build:
      context: ./
      dockerfile: Dockerworker

    image: assignment-4-worker
    restart: always
    ports: 
      - 8001:8001
    environment:
      MONGO_DATABASE: ${MONGO_DATABASE}
      MONGO_USER: ${MONGO_USER}
      MONGO_PASSWORD: ${MONGO_PASSWORD}
      MONGO_HOST: mongodb
      MONGO_PORT: 27017
      RABBITMQ_HOST: rabbit
    depends_on:
      - rabbit
      - mongodb
    links:
      - rabbit

volumes:
  mongo-data:
